q1,q2,q3,qa,qr
a,b,c
a,b,c,_
(q1,a)->(q2,a,R)
(q1,b)->(q1,b,R)
(q1,c)->(q1,c,R)
(q1,_)->(qr,_,L)
(q2,a)->(q3,a,R)
(q2,b)->(q2,b,R)
(q2,c)->(q2,c,R)
(q2,_)->(qr,_,L)
(q3,a)->(qa,a,R)
(q3,b)->(q3,b,R)
(q3,c)->(q3,c,R)
(q3,_)->(qr,_,L)
(qa,a)->(qa,_,R)
(qa,b)->(qa,_,R)
(qa,c)->(qa,_,R)
(qa,_)->(qa,_,L)
(qr,a)->(qr,_,L)
(qr,b)->(qr,_,L)
(qr,c)->(qr,_,L)
(qr,_)->(qr,_,L)
q1
qa
qr